Second task
Dovgalyuk/RETasks pull request #13
Opened 2021-01-03 09:09 UTC by OneChi

2021-01-04 10:54 UTC, Dovgalyuk requested changes

2021-01-04 10:54 UTC, Dovgalyuk commented on Decompilation/vtoraya.c
> +#include <stdio.h>
Нужен не готовый декомпилированный код, а разбор ассемблерного и ход восстановления алгоритма.

2021-01-05 09:23 UTC, OneChi commented on Decompilation/vtoraya.c
> +#include <stdio.h>
Исправил

2021-01-06 09:32 UTC, Dovgalyuk commented
2 задание принято, осталось 1 и 3.

2021-01-06 09:32 UTC, closed without merging