Дополнил задание 1 и 3
Dovgalyuk/RETasks pull request #15
Opened 2021-01-18 20:29 UTC by OneChi

2021-01-20 06:46 UTC, Dovgalyuk requested changes

2021-01-20 06:46 UTC, Dovgalyuk commented on Compilation/variant2.c
> +        переменные хранятся в rbp, rsp, eax, edx, [rbp-4]
Какая переменная хранится в rsp?

2021-01-20 14:10 UTC, OneChi commented on Compilation/variant2.c
> +        переменные хранятся в rbp, rsp, eax, edx, [rbp-4]
Голова стека

2021-01-21 07:01 UTC, Dovgalyuk commented on Compilation/variant2.c
> +        переменные хранятся в rbp, rsp, eax, edx, [rbp-4]
А надо описать в терминах исходного кода. В исходном коде нет стека.

2021-01-21 12:38 UTC, OneChi commented on Compilation/variant2.c
> +        переменные хранятся в rbp, rsp, eax, edx, [rbp-4]
Не правильно понял, извиняюсь, описал уже у ассемблерного кода

2021-10-08 04:47 UTC, closed without merging