Skakun A. S. Decompilation 18 and Overflow
Dovgalyuk/RETasks pull request #24
Opened 2021-11-17 20:04 UTC by IzzzGoy

2021-11-18 07:58 UTC, Dovgalyuk requested changes

2021-11-18 07:58 UTC, Dovgalyuk commented on BufferOverflow/auth_overflow2.c
> +   Результирующая команда: perl -e 'print "123456789012345678901234" . "\xa7\x05\x40" . "\x00"x5' | ./auth_overflow2
Маловато объяснений.

2021-11-18 07:58 UTC, Dovgalyuk commented on Decompilation/anwswer.c
> + *  Результат работы программы: YES если сумма любых 2х элементов больше третьего. NO иначе
Это принято.

2021-11-18 14:50 UTC, IzzzGoy commented
Во втором задании на переполнение стека добавлены пояснения

2021-11-19 08:00 UTC, Dovgalyuk commented
Принято.

2021-11-19 08:00 UTC, closed without merging