Лабораторная работа Dynamic
Dovgalyuk/RETasks pull request #32
Opened 2021-12-27 20:59 UTC by EvgeniiMendeleev

Отчёт о проделанной работе находится в файле "AFL (Отчёт)".

2021-12-28 06:22 UTC, Dovgalyuk requested changes

2021-12-28 06:22 UTC, Dovgalyuk commented on Fuzzy Loop/AFL (Отчёт)
> +Исходный код исправленного калькулятора располагается по следующему пути: RETasks/Fuzzy Loop/Calculator/calc-master/src/
Изменения и ошибки увидеть бы отдельно (например, в виде коммита). По целому исходнику искать не хочется.

2021-12-28 06:27 UTC, EvgeniiMendeleev commented on Fuzzy Loop/AFL (Отчёт)
> +Исходный код исправленного калькулятора располагается по следующему пути: RETasks/Fuzzy Loop/Calculator/calc-master/src/
Понял, хорошо. Сделаю.

2021-12-29 06:38 UTC, Dovgalyuk commented
Принято.

2021-12-29 06:38 UTC, closed without merging