Скомпилировал
Dovgalyuk/RETasks pull request #35
Opened 2022-09-18 19:38 UTC by Saorykun

Здравствуйте, скомпилировал асемблерный код, но не могу найти информацию по описанию команд. Подскажите где можно почитать?

2022-09-19 05:00 UTC, Dovgalyuk commented
Вот здесь есть неплохие ссылки: https://habr.com/ru/post/131971/

2022-09-19 14:39 UTC, Saorykun commented
Спасибо!

2022-09-22 21:22 UTC, Saorykun commented
Написал объяснения для нескольких функций, для всех прописать объяснения?

2022-09-24 04:23 UTC, Dovgalyuk commented
Да, для всех.

2022-09-24 04:25 UTC, Dovgalyuk commented
Для остальных можно описать только то, где хранятся переменные.

2022-09-26 07:17 UTC, Dovgalyuk commented
1. Не просто в каких регистрах, а какая именно переменная исходного кода в какой регистр попала
2. Напиши свою фамилию

2022-09-27 20:42 UTC, Saorykun commented
Меня зовут Кулаков Игорь Юрьевич, группа 2096
И я с вами веду у второго курса структуры данных и алгоритмы, подскажите к 9 неделе нужно отправить промежуточные результаты их работы?

2022-09-28 04:44 UTC, Dovgalyuk commented
> Меня зовут Кулаков Игорь Юрьевич, группа 2096 И я с вами веду у второго курса структуры данных и алгоритмы, подскажите к 9 неделе нужно отправить промежуточные результаты их работы?

Надо отправлять работы по одной. У кого к 9 неделе что-то будет, получат ненулевой балл.

2022-09-28 04:47 UTC, Dovgalyuk requested changes

2022-09-28 04:47 UTC, Dovgalyuk commented on Compilation/code.s
> +#переменная c в регистре edx
Тут же 3 переменные.

2022-09-28 04:47 UTC, Dovgalyuk commented on Compilation/code.s
> +#переменная c в регистре edx
и в этой функции 3 переменные

2022-10-03 06:47 UTC, Dovgalyuk commented
Принято, можно переходить к заданию Decompilation

2022-10-03 06:48 UTC, Dovgalyuk commented
> Меня зовут Кулаков Игорь Юрьевич, группа 2096 И я с вами веду у второго курса структуры данных и алгоритмы, подскажите к 9 неделе нужно отправить промежуточные результаты их работы?

Оказывается, я неправильно прочитал вопрос.
Для второкурсников результаты работы будут учитываться на 9 неделе, так что понадобится список с отметками о выполнении заданий.

2022-10-03 06:48 UTC, closed without merging