Decompilation 5 вариант
Dovgalyuk/RETasks pull request #41
Opened 2022-10-22 13:10 UTC by ivanovv893

2022-10-24 08:23 UTC, Dovgalyuk requested changes

2022-10-24 08:23 UTC, Dovgalyuk commented on Decompilation/ответы на вопросы.txt
> +- printf(), scanf()
Это библиотечные функции, а вопрос про те, что реализуют непосредственно вычисления.

2022-10-24 08:49 UTC, ivanovv893 commented on Decompilation/ответы на вопросы.txt
> +- printf(), scanf()
Понял, тогда, возведение в степень, сложение вычитание

2022-10-25 09:19 UTC, Dovgalyuk commented on Decompilation/ответы на вопросы.txt
> +- printf(), scanf()
Ну так надо тогда обозначить их в дизассемблированном коде, описать назначение каждой.

2022-10-25 17:57 UTC, ivanovv893 commented on Decompilation/ответы на вопросы.txt
> +- printf(), scanf()
Умножение
 720:	0f af c2             	imul   %edx,%eax
> подготовка значений в регистрах

Сдвиг (деление \ умножение на 2 в степени)
 67c:	48 c1 e8 3f          	shr    $0x3f,%rax
> Деление на 2^63

Сложение
 726:	83 45 fc 01          	addl   $0x1,-0x4(%rbp)
> изменение текущего адреса base pointer

Вычитание
 580:	48 83 ec 08          	sub    $0x8,%rsp
> изменение текущего адреса stack pointer

2022-10-26 12:27 UTC, Dovgalyuk commented on Decompilation/ответы на вопросы.txt
> +- printf(), scanf()
Это не функции. Функции вызываются с помощью call и завершают выполнение с помощью ret.

2022-10-26 13:55 UTC, ivanovv893 commented on Decompilation/ответы на вопросы.txt
> +- printf(), scanf()
Так получается 
819: 41 ff 14 dc callq *(%r12,%rbx,8) - вызывает функцию, указанную в rbx

2022-10-27 06:57 UTC, Dovgalyuk commented on Decompilation/ответы на вопросы.txt
> +- printf(), scanf()
Программа на C начинается с функции main. В дизассемблированном листинге она есть.
Надо определить, что в ней происходит. В том числе, какие именно функции там вызываются (и что они делают).

2022-11-10 18:27 UTC, ivanovv893 commented on Decompilation/ответы на вопросы.txt
> +- printf(), scanf()
[Функции.docx](https://github.com/Dovgalyuk/RETasks/files/9983668/default.docx)
Здравствуйте, дополнил ответ

2022-11-11 08:26 UTC, Dovgalyuk commented
Принято.

2022-11-11 08:26 UTC, closed without merging