Add effective version -O2
Dovgalyuk/RETasks pull request #6
Opened 2020-09-25 06:20 UTC by LaskovIlia

2020-09-28 09:42 UTC, Dovgalyuk requested changes

2020-09-28 09:42 UTC, Dovgalyuk commented on Compilation/variant2 -O2
> +        переменные хранятся в ECX,EDI,EAX,RAX,RCX
Одна же переменная тут, откуда столько регистров?

2020-12-07 05:57 UTC, Dovgalyuk requested changes

2020-12-07 05:57 UTC, Dovgalyuk commented on Compilation/variant2.c
> +        переменные хранятся в [RSP - 4], [RSP - 8], еах,edi
Тут всего две переменные. Откуда четыре варианта их хранения?

2020-12-14 05:55 UTC, Dovgalyuk commented
Стоит пройтись по всем функциям, и описать, в каких регистрах хранятся переменных (с сопоставлением их имен).

2020-12-20 10:56 UTC, LaskovIlia commented
Добавил

2020-12-21 10:58 UTC, Dovgalyuk commented
Принято.

2020-12-21 10:58 UTC, closed without merging